# Generated by Django 5.1.5 on 2025-01-22 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 29)),
        ),
    ]
